# config.py
# Premium GitHub V4 - Destek Direnç Futures
# GitHub Actions ile 5 dakikada bir çalışır.
# Bot emir açmaz, sadece Telegram sinyali gönderir.

BOT_NAME = "Premium GitHub V4 - Destek Direnç Futures"

# Tarama
AUTO_TOP_VOLUME_SCAN = True
MAX_SCAN_COINS = 300
MIN_24H_QUOTE_VOLUME = 300_000

# Zaman dilimleri
RADAR_TIMEFRAME = "5m"
ENTRY_TIMEFRAME = "15m"
CONFIRM_TIMEFRAME = "1h"
TREND_TIMEFRAME = "4h"

RADAR_LIMIT = 180
ENTRY_LIMIT = 420
CONFIRM_LIMIT = 320
TREND_LIMIT = 320

# Öncelikli coinler
COINS = [
    "BTCUSDT", "ETHUSDT", "SOLUSDT", "BNBUSDT", "XRPUSDT",
    "DOGEUSDT", "LINKUSDT", "AVAXUSDT", "ADAUSDT", "LTCUSDT",
    "DOTUSDT", "ARBUSDT", "OPUSDT", "NEARUSDT", "INJUSDT"
]

ALLOW_LONG = True
ALLOW_SHORT = True

# Gönderim
MAX_TRADE_SIGNALS_PER_RUN = 3
MAX_WATCH_ALERTS_PER_RUN = 5
MAX_OPEN_SIGNALS_NORMAL = 3
MAX_OPEN_SIGNALS_RISK = 2
SEND_STATUS_EVERY_MINUTES = 60
OPEN_SUMMARY_EVERY_MINUTES = 90

# Destek / direnç sistemi
SR_LOOKBACK = 80
SR_ZONE_PERCENT = 0.45
MAX_DISTANCE_TO_ENTRY_ZONE_PERCENT = 0.45
MIN_DISTANCE_TO_TARGET_PERCENT = 0.45

# Trend / hacim / skor
MIN_SCORE_TRADE = 78
MIN_SCORE_WATCH = 66
MIN_ADX_4H = 15
MIN_ADX_1H = 15
MIN_VOLUME_RATIO = 0.70
MIN_RR_TP1 = 0.85
MIN_RR_TP2 = 1.35

# Radar
RADAR_ENABLED = True
RADAR_MIN_MOVE_PERCENT = 0.35
RADAR_MAX_MOVE_PERCENT = 1.25
RADAR_MIN_VOLUME_RATIO = 1.25
RADAR_LONG_MAX_RSI = 70
RADAR_SHORT_MIN_RSI = 35

# Geç giriş engeli
MAX_ENTRY_DISTANCE_PERCENT = 0.35
MAX_TP1_PROGRESS_PERCENT = 40

# Risk / kaldıraç
MIN_RISK_PERCENT = 0.25
MAX_RISK_PERCENT = 3.00

# Riskli piyasa modu
# Sistem ASLA tamamen durmaz. Stop artarsa daha seçici moda geçer.
RISK_MODE_STOP_COUNT = 2
RISK_MODE_MAX_TRADE_SIGNALS = 1
RISK_MODE_MAX_WATCH_ALERTS = 3
RISK_MODE_ALLOW_RADAR_TRADE = False

# Tekrar engelleri
DUPLICATE_BLOCK_SECONDS = 2 * 60 * 60
WATCH_DUPLICATE_BLOCK_SECONDS = 45 * 60
BLOCK_STOPPED_COIN_HOURS = 6

# Günlük rapor
DAILY_REPORT_HOUR = 23
DAILY_REPORT_MINUTE = 45
